name: neuvoice_new
description: Privacy-first speech-to-text with Raspberry Pi backend
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  dio: ^5.4.0
  web_socket_channel: ^2.4.0
  path_provider: ^2.1.5            # Compatible with Flutter 3 and record 4.4.18
  permission_handler: ^12.0.1
  record: ^4.4.4                   # Matches your request
  record_linux: ^0.4.1             # Compatible with record 4.4.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fftea: ^1.5.0
  uuid: ^4.2.1

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
